spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USER:dfalconr}
    password: ${DB_PASSWORD:MyN3wP@ssw0rd!}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  authentication:
    jwt:
      secret: ${JWT_SECRET:c3ByaW5nYm9vdC1qd3QtdGVzdC1hcHAtc2VjcmV0}
      expiration: 86400000